name: vdp
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+17

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  blue_thermal_printer: ^1.2.0
  cloud_firestore: ^3.1.7
  cloud_functions: ^3.2.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  flutter:
    sdk: flutter
  horizontal_data_table: ^4.1.2+2
  permission_handler: ^10.2.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: false
  image_path: "images/play_store_512.png"

flutter:
  uses-material-design: true
  assets:
    - images/google-pay.png
    - images/google-pay-icon.png
    - images/cash.png

  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
